language: scala
sbt_args: -J-Dproject.version=travis-SNAPSHOT
scala:
  - 2.11.7
  - 2.12.0-M3
jdk:
  # - oraclejdk7
  - oraclejdk8
  # - openjdk7
# sudo: false
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
env:
  matrix:
    - SCALAZ_VERSION="7.1.4"
    - SCALAZ_VERSION="7.2.0"
before_script:
  - sed -i -e "s/scalazVersion = \".*\"/scalazVersion = \"${SCALAZ_VERSION}\"/" build.sbt
script:
  - sbt ++$TRAVIS_SCALA_VERSION "testOnly fs2.*"
