jobs:
  publish:
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    runs-on: ubuntu-18.04
    steps:
      - uses: "actions/checkout@v2.1.0"
      - uses: "cachix/install-nix-action@v9"
      - uses: "cachix/cachix-action@v6"
        with:
          name: fs2-site
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: "Building microsite 🚧"
        run: "nix-shell --run \"echo $JAVA_HOME && sbt microsite/publishMicrosite --java-home $JAVA_HOME\""
name: Microsite
on:
  push:
